%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

Camera2.nCols: 640
Camera2.nRows: 480


# InitialBias.x: 0
# InitialBias.y: 0
# InitialBias.z: 0.2
# InitialBias.qw: 1
# InitialBias.qx: 0
# InitialBias.qy: -0.015 # -0.01
# InitialBias.qz: 0

# InitialAnchor.x: 19.375
# InitialAnchor.y: -10.17
# InitialAnchor.z: 0.114 # 0.2
# InitialAnchor.qw: 0.5
# InitialAnchor.qx: 0.5
# InitialAnchor.qy: 0.5
# InitialAnchor.qz: 0.5

InitialAnchor.x: 0
InitialAnchor.y: 0
InitialAnchor.z: 0
InitialAnchor.qw: 1
InitialAnchor.qx: 0
InitialAnchor.qy: 0
InitialAnchor.qz: 0

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 554.254691191187
Camera.fy: 554.254691191187
Camera.cx: 320.5
Camera.cy: 240.5

Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p2: 0


# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor 
DepthMapFactor: 1 # 5000.0 # 1.0 # 

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 800 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid   
ORBextractor.scaleFactor: 1.2 # 2 #  

# ORB Extractor: Number of levels in the scale pyramid  
ORBextractor.nLevels: 8 # 3 #  

# ORB Extractor: Fast threshold for ORB-SLAM 1 (lower less restrictive)     
ORBextractor.fastTh: 20

# ORB Extractor: Score to sort features. 0 -> Harris Score, 1 -> FAST Score     
ORBextractor.nScoreType: 1

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

# Constant Velocity Motion Model (0 - disabled, 1 - enabled [recommended])
UseMotionModel: 1

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
